# Use postgres/example user/password credentials
version: '1.0'
services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - 
    environment:
      POSTGRES_PASSWORD: <secret>


docker run --name pgsql-db-1.1 \
-p 5432:5432 \
-e POSTGRES_PASSWORD=<secret> \
-v /var/lib/postgresql/data:/var/lib/postgresql/data \
-d postgres;

CREATE DATABASE airflow_db;
CREATE USER airflow_user WITH PASSWORD '<secret>';
GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;
-- PostgreSQL 15 requires additional privileges:
GRANT ALL ON SCHEMA public TO airflow_user;